### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by tomasbedrich** [nielsfaber/scheduler-component#179]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
No error in logs.

### Actual behavior
```
2022-02-12 11:17:41 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/scheduler/actions.py", line 485, in async_timer_finished
    await self.async_process_queue(task_idx + 1)
  File "/config/custom_components/scheduler/actions.py", line 510, in async_process_queue
    skip_action = not action_has_effect(action, self.hass)
  File "/config/custom_components/scheduler/actions.py", line 206, in action_has_effect
    return float(state.attributes.get(ATTR_TEMPERATURE)) != float(
TypeError: float() argument must be a string or a number, not 'NoneType'
2022-02-12 11:17:41 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/scheduler/actions.py", line 485, in async_timer_finished
    await self.async_process_queue(task_idx + 1)
  File "/config/custom_components/scheduler/actions.py", line 510, in async_process_queue
    skip_action = not action_has_effect(action, self.hass)
  File "/config/custom_components/scheduler/actions.py", line 206, in action_has_effect
    return float(state.attributes.get(ATTR_TEMPERATURE)) != float(
TypeError: float() argument must be a string or a number, not 'NoneType'
```

### Steps to Reproduce
- Restart Home Assistant.

### Attachment
[scheduler.storage.json.zip](https://github.com/nielsfaber/scheduler-component/files/8053174/scheduler.storage.json.zip)

**Comment by nielsfaber** [comment]
This problem seems to be related to your HA configuration.
You seem to have a climate device which exposes that the current temperature is 'none' (or 'null').
Scheduler expects this to be a number.
I could change things to suppress the error, but I think the root cause is in your climate entity.

**Comment by tomasbedrich** [comment]
Hm, while I understand it is an unexpected behavior of my climate entity, it may be quite common. Given I use Zigbee2MQTT, I would expect more people's climate entities to behave the same. Anyway, I am happy with this explanation, therefore closing this issue and you can consider it FYI only. :)

**Comment by mj1985** [comment]
Hey,

I got the same error with my Eurotronic thermostat, they were working fine last winter with the scheduler component.

```
Logger: homeassistant
Source: custom_components/scheduler/actions.py:210
Integration: Scheduler integration (documentation, issues)
First occurred: 00:00:10 (2 occurrences)
Last logged: 01:40:10

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/scheduler/actions.py", line 489, in async_timer_finished
    await self.async_process_queue(task_idx + 1)
  File "/config/custom_components/scheduler/actions.py", line 514, in async_process_queue
    skip_action = not action_has_effect(action, self.hass)
  File "/config/custom_components/scheduler/actions.py", line 210, in action_has_effect
    return float(state.attributes.get(ATTR_TEMPERATURE)) != float(
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

Is there anything I can do?

**Comment by nielsfaber** [comment]
@mj1985 you could update to v3.2.11 to solve the problem.
Be aware that the issue is not caused by scheduler, see also here https://github.com/nielsfaber/scheduler-component/issues/214#issuecomment-1312367528.
