### ISSUE TITLE
Triggering a schedule has no effect

### ISSUE THREAD

**Issue by xlash123** [nielsfaber/scheduler-component#342]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
I set a schedule to turn on a light at a certain time, and when that time passes, the light should turn on.
Here is the schedule I set:
![image](https://github.com/nielsfaber/scheduler-component/assets/4966137/e8a79ff3-370d-4441-bdc3-dd2495fc9379)

### Actual behavior
The time passes, and the light does not turn on, despite the event log showing it was triggered.
![image](https://github.com/nielsfaber/scheduler-component/assets/4966137/795c8af4-6087-4337-a1b3-43f87918f43f)
I can toggle the light switch manually on the HA entity, and the light does turn on. I even tried triggering the schedule manually through Call Service in the Developer Tools, and no effect occurs. There is no evidence of the light being turned on in either the scheduler's event log or the light's event log.

I checked the HA logs, and there are no errors for this integration. These are the only relevant logs I could find:
<details><summary>Details</summary>
<p>

```
2024-03-29 13:03:28.040 DEBUG (MainThread) [custom_components.hacs] <Integration nielsfaber/scheduler-component> Running checks against v3.3.2
2024-03-29 13:03:28.082 DEBUG (MainThread) [custom_components.hacs] <Plugin nielsfaber/scheduler-card> Running checks against v3.2.12
2024-03-29 13:03:28.089 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.34.0
2024-03-29 13:03:28.357 DEBUG (MainThread) [custom_components.hacs] <Integration nielsfaber/scheduler-component> Getting documentation for version=v3.3.2,filename=README.md
2024-03-29 13:03:28.357 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/nielsfaber/scheduler-component/v3.3.2/README.md
2024-03-29 13:03:28.425 DEBUG (MainThread) [custom_components.hacs] <Plugin nielsfaber/scheduler-card> Getting documentation for version=v3.2.12,filename=README.md
2024-03-29 13:03:28.425 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/nielsfaber/scheduler-card/v3.2.12/README.md
2024-03-29 13:03:28.439 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting documentation for version=1.34.0,filename=info.md
2024-03-29 13:03:28.439 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/hacs/integration/1.34.0/info.md
2024-03-29 13:03:28.570 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Queue execution finished for 3 tasks finished in 0.95 seconds
2024-03-29 13:03:28.570 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2024-03-29 13:04:23.202 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2024-03-29 13:04:23.202 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2024-03-29 13:05:10.282 INFO (Recorder) [homeassistant.components.sensor.recorder] Detected new cycle for sensor.sonoff_s31_energy_today_2, value dropped from 0.137 to 0.001, triggered by state with last_updated set to 2024-03-29T17:03:30.200411+00:00
```

</p>
</details> 

The last line was caused by me updating the trigger time to a minute ahead to do another test. No new logs were caused by the trigger.

Is there a way I can enable more debug logs? I feel bad that I can't provide any more info. It's obvious that this is some rare edge case (or major misconfiguration on my end) since I can't find any evidence of this integration just not working in the most simple use case.

### Steps to Reproduce
1. Create a schedule for a specific time and action
2. Wait for the schedule to be triggered OR trigger schedule with Call Service in Developer Tools

**Comment by derk1983** [comment]
Scheduler component is not working with heating. When I save a schedule then it 8s working. But when the next trigger (time) comes, it doesn't work.

**Comment by Stooovie** [comment]
Same with a Xiaomi Air Cleaner (a "fan"). I have noticed the Scheduler is generally very flaky and not reliable lately. What could it be?

**Comment by DavidGeorge528** [comment]
> Scheduler component is not working with heating. When I save the schedule then it is working. But when the next trigger (time) comes, it doesn't work.

Having a similar issue, not sure if its related. I had a schedule setup to turn on 6 TRVs every morning. Noticed a few days ago the house was cold except the bathroom. After looking, the schedule only seems to work on the first device and none others. 

Below is an example with 2 TRVs:

<img width="531" alt="image" src="https://github.com/nielsfaber/scheduler-component/assets/7761453/b5c631cb-7999-4335-9a94-1b6ea4024514">

The example uses two TRVs, and at the time of testing, the schedule should've turned both onto heat at 22C, they were previously set to Heat at 16C

<img width="495" alt="Screenshot 2024-04-02 at 23 52 02" src="https://github.com/nielsfaber/scheduler-component/assets/7761453/533b9ad4-5e2c-4cf4-93a4-d35df51c01aa">

After saving the schedule, it triggers and turns the Kitchen TRV to 22C (The Kitchen is the first in the list of entities, the order of which is the order you click them in the interface). But the Living Room remains at 16C.

<img width="569" alt="image" src="https://github.com/nielsfaber/scheduler-component/assets/7761453/4449495b-a70a-4012-91f3-b59c91aaffc6">

Interestingly, although the graph shows the Kitchen TRV turned on, the log doesn't reflect this. The Living Room TRV has no activity in the graph nor the log.

**It is worth noting, I believe these issues started when I updated to the latest Home Assistant April release beta. I haven't yet tried reverting to the stable March release.**

Some information: 

Home Assistant Core: 2024.4.0b5
Schedule Component: v3.3.2
Schedule Card: v3.2.12

**Comment by DavidGeorge528** [comment]
Latest update v3.3.3 fixed my issue

**Comment by derk1983** [comment]
> Scheduler component is not working with heating. When I save the schedule then it is working. But when the next trigger (time) comes, it doesn't work.

Latest update fixed this. Thnx!

**Comment by dizzydnallov** [comment]
Not fixed for me on 3.3.3

I got home and found all my heating had been on but should have been turned off at 10:30am.   Nothing on the logs.

**Comment by xlash123** [comment]
I also did not have any success with triggering a schedule on 3.3.3.

**Comment by nielsfaber** [comment]
@xlash123 your initial bug report shows that the entity that is controlled by the schedule is 'Philips Hue A Power-on behaviour' and the reported issue is 
> The time passes, and the light does not turn on, despite the event log showing it was triggered.

Based on your configuration I wouldn't expect the lamp to turn on, but this has nothing to do with scheduler but with the device.
The 'power on behavior' only determines how the lamp responds when after power cut. 
Could you change your schedule to control the lamp (i.e. light entity) itself?

**Comment by gravymaker17** [comment]
> Not fixed for me on 3.3.3
> 
> I got home and found all my heating had been on but should have been turned off at 10:30am. Nothing on the logs.

Same symptoms for me.    Schedule for baseboard heater control worked fine until a couple weeks ago.   I come home and find the schedule runs, but the heaters are not changed.  this error is in thenlog right around the scheduled event time:

[code]
Exception in async_timer_finished when dispatching 'scheduler_timer_finished': ('9393f9',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 278, in async_timer_finished await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 260, in async_queue_actions for queue in self._queues.values(): RuntimeError: dictionary changed size during iteration
[/code]

**Comment by petebanham** [comment]
I having the same problem with my climate controls.  I am on 3.3.3.  but the temp updated do not trigger.  Switching the schedule  on and off used to make it sent a temperature update command but that does do anything now either.  Nothing show in the logs, it like it just doesn't trigger.

**Comment by petebanham** [comment]
> I having the same problem with my climate controls. I am on 3.3.3. but the temp updated do not trigger. Switching the schedule on and off used to make it send a temperature update command but that does do anything now either. Nothing show in the logs, it like it just doesn't trigger.

Actually, some further testing shows that the problem is intermittent for me. I'm not sure exactly when it started but until recently it has been rock solid.  I'm running core 2024.4.4
