### ISSUE TITLE
Error while setting up scheduler platform for switch

### ISSUE THREAD

**Issue by LeeWiu** [nielsfaber/scheduler-component#376]
Hi, new scheduler v3.3.6 install and shows only Climate group. Scheduler card v3.2.13, HA v2024.9.1

Error in log:
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:361
integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 22:02:30 (3 occurrences)
Last logged: 22:06:17

Error while setting up scheduler platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/scheduler/switch.py", line 98, in async_setup_entry
    SERVICE_RUN_ACTION, RUN_ACTION_SCHEMA, "async_service_run_action"
                        ^^^^^^^^^^^^^^^^^
NameError: name 'RUN_ACTION_SCHEMA' is not defined

<img width="546" alt="Screenshot 2024-09-08 at 22 10 17" src="https://github.com/user-attachments/assets/9d047afd-c651-4aa6-9b19-1c0da66656f5">

**Comment by LeeWiu** [comment]
Sorry, wrong place. Groups should be created/enabled in Scheduler Card https://github.com/nielsfaber/scheduler-card?tab=readme-ov-file#groups
