### ISSUE TITLE
extra keys not allowed @ data['mode'] on schema update

### ISSUE THREAD

**Issue by dj4ngo** [nielsfaber/scheduler-component#52]
I am using HASS v0.117.6 
I just performed a fresh install, to reproduce in a minimal environment, then installed latest HACS (v1.6.2) and installed both scheduler integration and card. 

I want to control some input_select only.

I am using schema instead of option. I can create some entries, set every scheme I want, but as soon as I want to edit a schema I am facing this issue. 
I can  edit options (to add a condition or change the name) without issue
I can change the type from scheme to condition without issue

This issue occurs only when I try to edit the time of modes I want to set.

I am not sure if this is an issue of the scheduler component or scheduler card. 

----------------------------------------
Issue message : 
```
2020-11-13 17:38:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2892112608] extra keys not allowed @ data['mode']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
    await result
  File "/config/custom_components/scheduler/switch.py", line 458, in async_service_edit
    await self.async_abort_queued_actions()
  File "/config/custom_components/scheduler/switch.py", line 246, in async_start_timer
    _LOGGER.debug("We are starting in a timeslot. Proceed with actions.")
  File "/config/custom_components/scheduler/switch.py", line 318, in async_execute_command
  File "/config/custom_components/scheduler/switch.py", line 361, in async_queue_action
    if res:
  File "/config/custom_components/scheduler/switch.py", line 401, in async_execute_action
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 91, in async_call_from_config
    await hass.services.async_call(*parms, blocking, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1402, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['mode']
```

----------------------------------------
Environment : 
```
$ ha info 
arch: armv7
channel: stable
docker: 19.03.12
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: "4.16"
homeassistant: 0.117.6
hostname: homeassistant
logging: info
machine: raspberrypi4
operating_system: HassOS 4.16
supervisor: 2020.11.0
supported: true
supported_arch:
- armv7
- armhf
timezone: Europe/Paris
```

**Comment by nielsfaber** [comment]
Thanks for reporting.
I found the cause and fixed it: https://github.com/nielsfaber/scheduler-card/commit/b44af89072c8184094679f66811986dfb5f69231

I will try to push out a new release somewhere this weekend (I always try combine it with other stuff).

**Comment by dj4ngo** [comment]
Hi, wow, you're fast ! 
Well done !

**Comment by nielsfaber** [comment]
I just released v1.9.6 of the card, which should solve this bug.
Its best to remove all previously created schedules involving `input_select`, because the improvement in the code only has effect while creating a schedule.

**Comment by dj4ngo** [comment]
Thanks, it working well. 

I close the issue.

By the way, do you have any documentation on how to test scheduler-card for a local build to generate locally the scheduler-card.js ? 
This could help me to propose directly patch instead of opening only issues.

**Comment by nielsfaber** [comment]
> By the way, do you have any documentation on how to test scheduler-card for a local build to generate locally the scheduler-card.js ?
This could help me to propose directly patch instead of opening only issues.

- Do a full checkout of the repo
- run `npm i` to install the dependencies.
- run `npm start` to start the rollup script, which keeps watching for source file changes (in `/src`) and recompiles the output js file (in `/dist`) when needed
- Its important to disable caching of your browser while making changes, because otherwise you find yourself wondering why your changes didn't have any effect.
- To speed up recompiling you could temporarily comment out `terser()` from the `rollup.config.js`.

There is not more to it AFAIK.
I use vscode  for editing. It seems to work very well for typescript.

Would be great if you can help.
There is much room for improvement, I keep finding myself restructurizing messy parts.
If you want to do a big change / new feature, maybe better to discuss it before.

**Comment by dj4ngo** [comment]
Hi, thanks again a lot for these explanations.

Of course, I'll open an issue as feature proposal to discuss about before running on the implementation. 
I am about to make one, I just need to perform some checks to ensure proposing the most generic way to benefit to the most people as possible.
