### ISSUE TITLE
Conditions for binary_sensor

### ISSUE THREAD

**Issue by maureis** [nielsfaber/scheduler-component#64]
I added some window sensor (binary_sensor on/off) to _include_ directly in yaml and then to schedule conditions. There was no possibility to add that sensor through GUI. I have something like this:

```
2020-11-27 00:33:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/scheduler/switch.py", line 564, in async_check_entities_available
await cb_func()
File "/config/custom_components/scheduler/switch.py", line 341, in async_handle_device_available
await self.async_execute_action(service_call)
File "/config/custom_components/scheduler/switch.py", line 373, in async_execute_action
condition_entities = self.dataCollection.get_condition_entities_for_entry(
File "/config/custom_components/scheduler/datacollection.py", line 517, in get_condition_entities_for_entry
if not self.conditions or not "conditions" in self.entries[entry]:
TypeError: list indices must be integers or slices, not NoneType
```

Are binary sensors supported? I would like to determine thermostat schedule trigger only when window is closed - retrigger when closed.

**Comment by KTibow** [comment]
Bug, the entry is null, maybe try again?

**Comment by nielsfaber** [comment]
It's currently not working as it should.
I am working on an improvement for this behaviour.

**Comment by nielsfaber** [comment]
I improved the conditions implementation in v3.0.0.
Please consider updating, and test if this resolves your problem.

**Comment by maureis** [comment]
@nielsfaber works good, thanks :)

**Comment by KTibow** [comment]
Does that mean this can be closed?
