### ISSUE TITLE
[bug 3.0.0] Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Kalypox** [nielsfaber/scheduler-component#79]
Hi,

I have this bug with the new component:

```
2020-12-24 14:40:26 INFO (MainThread) [homeassistant.components.generic_thermostat.climate] Obtained current and target temperature. Generic thermostat active. 22.47, 19.0
2020-12-24 14:40:26 INFO (MainThread) [homeassistant.components.generic_thermostat.climate] Obtained current and target temperature. Generic thermostat active. 18.06, 21.0
2020-12-24 14:40:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/scheduler/switch.py", line 708, in async_check_entities_available
await cb_func()
File "/config/custom_components/scheduler/switch.py", line 464, in async_handle_device_available
await self.async_execute_action(service_call, self._queued_entry)
File "/config/custom_components/scheduler/switch.py", line 493, in async_execute_action
current_slot = self.schedule["timeslots"][timeslot]
TypeError: list indices must be integers or slices, not NoneType
2020-12-24 14:40:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/scheduler/switch.py", line 708, in async_check_entities_available
await cb_func()
File "/config/custom_components/scheduler/switch.py", line 464, in async_handle_device_available
await self.async_execute_action(service_call, self._queued_entry)
File "/config/custom_components/scheduler/switch.py", line 493, in async_execute_action
current_slot = self.schedule["timeslots"][timeslot]
TypeError: list indices must be integers or slices, not NoneType
2020-12-24 14:40:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/scheduler/switch.py", line 708, in async_check_entities_available
await cb_func()
File "/config/custom_components/scheduler/switch.py", line 464, in async_handle_device_available
await self.async_execute_action(service_call, self._queued_entry)
File "/config/custom_components/scheduler/switch.py", line 493, in async_execute_action
current_slot = self.schedule["timeslots"][timeslot]
TypeError: list indices must be integers or slices, not NoneType
2020-12-24 14:40:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/scheduler/switch.py", line 708, in async_check_entities_available
await cb_func()
File "/config/custom_components/scheduler/switch.py", line 464, in async_handle_device_available
await self.async_execute_action(service_call, self._queued_entry)
File "/config/custom_components/scheduler/switch.py", line 493, in async_execute_action
current_slot = self.schedule["timeslots"][timeslot]
TypeError: list indices must be integers or slices, not NoneType
```

This issue appears after setting the schedule and rebooted home assistant

**Comment by KTibow** [comment]
Can you post a screenshot of your schedule?

**Comment by Kalypox** [comment]
![image](https://user-images.githubusercontent.com/2879180/103095545-3a2ef680-4601-11eb-8472-38418df9b5c1.png)

**Comment by nielsfaber** [comment]
Thanks for reporting this.
Something is wrong in the scheduler-component.
Can you tell me when the error occurs?
Right after startup? When schedule triggers? After turning on? After editing?

**Comment by Kalypox** [comment]
@nielsfaber

Right after startup?
Yes after startup of HA

When schedule triggers? 
The schedules doesn't triggers

After turning on?
No

After editing?
Neither

**Comment by nielsfaber** [comment]
Can you share your `scheduler.storage` file?
Can you also check which version you are using?
It can be checked by clicking on the scheduler device:
![image](https://user-images.githubusercontent.com/16861605/103165555-abe18d00-4819-11eb-945d-28210a5a2a3c.png)

**Comment by Kalypox** [comment]
I found the problem !
It came from a custom_component : generic_thermostat
My version wasn't adapted to home assistant, i remade it !

Thanks !


This is my scheduler storage:
```
{
    "version": 1,
    "key": "scheduler.storage",
    "data": {
        "schedules": [
            {
                "schedule_id": "52f39e",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "07:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_hvac_mode",
                                "entity_id": "climate.toilettes_thermostat",
                                "service_data": {
                                    "hvac_mode": "off"
                                }
                            }
                        ]
                    },
                    {
                        "start": "07:00:00",
                        "stop": "20:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.toilettes_thermostat",
                                "service_data": {
                                    "hvac_mode": "heat",
                                    "temperature": 19
                                }
                            }
                        ]
                    },
                    {
                        "start": "20:00:00",
                        "stop": "00:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_hvac_mode",
                                "entity_id": "climate.toilettes_thermostat",
                                "service_data": {
                                    "hvac_mode": "off"
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "Toilettes",
                "enabled": true
            },
            {
                "schedule_id": "b61d1b",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "05:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_hvac_mode",
                                "entity_id": "climate.sdb_thermostat",
                                "service_data": {
                                    "hvac_mode": "off"
                                }
                            }
                        ]
                    },
                    {
                        "start": "05:00:00",
                        "stop": "08:30:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.sdb_thermostat",
                                "service_data": {
                                    "hvac_mode": "heat",
                                    "temperature": 23
                                }
                            }
                        ]
                    },
                    {
                        "start": "08:30:00",
                        "stop": "17:30:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_hvac_mode",
                                "entity_id": "climate.sdb_thermostat",
                                "service_data": {
                                    "hvac_mode": "off"
                                }
                            }
                        ]
                    },
                    {
                        "start": "17:30:00",
                        "stop": "21:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.sdb_thermostat",
                                "service_data": {
                                    "hvac_mode": "heat",
                                    "temperature": 23
                                }
                            }
                        ]
                    },
                    {
                        "start": "21:00:00",
                        "stop": "00:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_hvac_mode",
                                "entity_id": "climate.sdb_thermostat",
                                "service_data": {
                                    "hvac_mode": "off"
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "Salle de bain",
                "enabled": true
            },
            {
                "schedule_id": "edb9f3",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "07:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "switch.turn_off",
                                "entity_id": "switch.terrarium_lumiere",
                                "service_data": {}
                            }
                        ]
                    },
                    {
                        "start": "07:00:00",
                        "stop": "22:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "switch.turn_on",
                                "entity_id": "switch.terrarium_lumiere",
                                "service_data": {}
                            }
                        ]
                    },
                    {
                        "start": "22:00:00",
                        "stop": "00:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "switch.turn_off",
                                "entity_id": "switch.terrarium_lumiere",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "Terrarium",
                "enabled": true
            },
            {
                "schedule_id": "d4e8b4",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "18:50:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_preset_mode",
                                "entity_id": "climate.chambre_jonathan_radiateur",
                                "service_data": {
                                    "preset_mode": "away"
                                }
                            }
                        ]
                    },
                    {
                        "start": "18:50:00",
                        "stop": "19:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_preset_mode",
                                "entity_id": "climate.chambre_jonathan_radiateur",
                                "service_data": {
                                    "preset_mode": "manual"
                                }
                            }
                        ]
                    },
                    {
                        "start": "19:00:00",
                        "stop": "00:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.chambre_jonathan_radiateur",
                                "service_data": {
                                    "hvac_mode": "heat",
                                    "temperature": 22
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "Chambre Jonathan",
                "enabled": false
            }
        ]
    }
}
```

And my version was the last one
