### ISSUE TITLE
Creating a new schedule, error ""extra keys not allowed @ data['actions']""

### ISSUE THREAD

**Issue by uglynerds** [nielsfaber/scheduler-component#83]
Logger: homeassistant.components.websocket_api.http.connection
Source: core.py:1289
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:37:58 (1 occurrences)
Last logged: 16:37:58
extra keys not allowed @ data['actions']

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 138, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1289, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['actions']

**Comment by nielsfaber** [comment]
cannot help you without some details..

**Comment by uglynerds** [comment]
Niels, solved by full reinstall, as upgrade via HACS didnt work
