### ISSUE TITLE
Service usage doesn’t work since last update 09.03

### ISSUE THREAD

**Issue by Djal94** [nielsfaber/scheduler-component#92]
Hello, the way i use the service until yesterday doesn’t work anymore, and i cannot found the way to make it work.

Some changes during the last update?

`
service: scheduler.add
data:
  weekdays:
    - daily
  repeat_type: single
  timeslots:
    - start: '07:40'
      actions:
        - service: script.turn_on
          entity_id: script.tji
`

**Comment by nielsfaber** [comment]
The last changes in the scheduler-component were made on January 3.

Maybe something changed in HA that broke stuff, but I’m not aware of any recent breaking changes.

**Comment by Djal94** [comment]
Could please provide an basic example to use the service add please? Maybe related to the last core update

**Comment by nielsfaber** [comment]
The example data provided with the service has been tested before and should work.
I don't have the time right now to investigate what might have changed on HA's side.

**Comment by Djal94** [comment]
Ok. So it seems that it is not related to the last core updated. I downgrade to the core-2021.2.3 and stil have the issue.

the issue happen after update 3.0.4 update of the component 2 days ago.

How can i rollback please?

**Comment by Djal94** [comment]
if this can help 

`2021-03-10 22:49:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139657769889504] 'mappingproxy' object does not support item assignment
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await self._hass.async_add_executor_job(handler.job.target, service_call)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/scheduler/__init__.py", line 77, in service_create_schedule
coordinator.async_create_schedule(service.data)
File "/config/custom_components/scheduler/__init__.py", line 208, in async_create_schedule
res = self.store.async_create_schedule(data)
File "/config/custom_components/scheduler/store.py", line 189, in async_create_schedule
data = parse_schedule_data(data)
File "/config/custom_components/scheduler/store.py", line 79, in parse_schedule_data
data["timeslots"] = timeslots
TypeError: 'mappingproxy' object does not support item assignment`

**Comment by Djal94** [comment]
Si made the correction suggested in the #82 issue. and it'ok for me. issue does not occurs now. did not remember that i did that berfore the 3.04

**Comment by nielsfaber** [comment]
Duplicate of https://github.com/nielsfaber/scheduler-component/issues/82
